import numpy as np

# Exercise 01: Create a null vector that contains 10 elements
print("Exercise 01: Create a null vector that contains 10 elements")
null_vector = np.zeros(10)
print(null_vector)
print('*****')

# Exercise 02: Create a vector of ones with 10 elements
print("Exercise 02: Create a vector of ones with 10 elements")
vector_ones = np.ones(10)
print(vector_ones)
print('*****')

# Exercise 03: Investigate the linspace function of numpy and create an array with 10 elements
print("Exercise 03: Investigate the linspace function of numpy and create an array with 10 elements")
array_linspace = np.linspace(0, 10, 10)
print(array_linspace)
print('*****')

# Exercise 04.1: Generate a 1d array with random values using random.rand()
print("Exercise 04: Generate a 1d array with random values using random.rand()")
array_random = np.random.rand(10)
print(array_random)
print("Exercise 04: Generate a 2d array with random values using random.rand()")
array_random = np.random.rand(3, 3)
print(array_random)
print('*****')
# Exercise 04.2: Generate a 1d array with random values using random.randint()
print("Exercise 04: Generate a 1d array with random values using random.randint()")
array_random = np.random.randint(10, size=10)
print(array_random)
print("Exercise 04: Generate a 2d array with random values using random.randint()")
array_random = np.random.randint(10, size=(3, 3))
print(array_random)
print('*****')
# Exercise 04.3: Generate a 1d array with random values using random.randn()
print("Exercise 04: Generate a 1d array with random values using random.randn()")
array_random = np.random.randn(10)
print(array_random)
print("Exercise 04: Generate a 2d array with random values using random.randn()")
array_random = np.random.randn(3, 3)
print(array_random)
print('*****')
# Exercise 05: Create a 5x5 identity matrix (2D array)
print("Exercise 05: Create a 5x5 identity matrix (2D array)")
array_identity = np.eye(5) # 5 is the number of rows and columns in the matrix
print(array_identity)
print('*****')
# Exercise 06: Create a 3x2 random number matrix and calculate the minimum and maximum values
print("Exercise 06: Create a 3x2 random number matrix and calculate the minimum and maximum values")
array_random = np.random.randint(10, size=(3, 2))
print(array_random)
print("Minimum value: ", np.min(array_random))
print("Maximum value: ", np.max(array_random))
print('*****')
# Exercise 07: Create a 3x3 matrix with values ranging from 0 to 8
print("Exercise 07: Create a 3x3 matrix with values ranging from 0 to 8")
array_3x3 = np.arange(9).reshape(3, 3)
print(array_3x3)    
print('*****')
# Exercise 08: Create a 3x3x3 array with random values
print("Exercise 08: Create a 3x3x3 array with random values")
array_random = np.random.randint(10, size=(3, 3, 3))
print(array_random)
print('*****')
# Exercise 09: Create a vector of 30 elements that are random numbers and calculate the mean.
print("Exercise 09: Create a vector of 30 elements that are random numbers and calculate the mean.")
array_random = np.random.randint(10, size=30)
print(array_random)
print("Mean: ", np.mean(array_random))
print('*****')
# Exercise 10: Convert the list [1, 2, 3] and the tuple (1, 2, 3) to arrays
print("Exercise 10: Convert the list [1, 2, 3] and the tuple (1, 2, 3) to arrays")
list_1 = [1, 2, 3]
tuple_1 = (1, 2, 3)
array_list = np.array(list_1)
array_tuple = np.array(tuple_1)
print(array_list)
print(array_tuple)
print('*****')
